<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA5fAssG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA5fAssG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA5fAssG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA5fAssG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA5fAssG\App_KernelDevDebugContainer([
    'container.build_hash' => 'A5fAssG',
    'container.build_id' => 'f8e9ffe4',
    'container.build_time' => 1786643394,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA5fAssG');
