<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAKRxxFS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAKRxxFS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAKRxxFS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAKRxxFS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAKRxxFS\App_KernelDevDebugContainer([
    'container.build_hash' => 'AKRxxFS',
    'container.build_id' => '21435e0e',
    'container.build_time' => 1786862203,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAKRxxFS');
